"""Generate the static portfolio. Python standard library only. No build needed to host."""
from pathlib import Path
from html import escape

ROOT = Path(__file__).resolve().parent
RESUME = 'https://drive.google.com/file/d/1_lbn_LmDKM71WYN3ldU_NOQHzYq1nyq_/view?usp=sharing'

PROJECTS = [
 dict(slug='google-maps', name='Google Maps', category='Navigation', color='#e6ecf3', title='Adaptive Safety & Comfort Navigation', short='A more informed choice between journey time and road comfort.', question='When is a smoother route worth a few extra minutes?', focus='Route choice & data confidence',
 problem='For passengers who find rough roads uncomfortable, the fastest route may not be the preferred route. This concept explores how navigation could make road conditions, journey time and uncertainty easier to compare.',
 hypothesis='If people can compare a standard route with a comfort-focused alternative, they may feel more confident choosing the journey that suits their passengers—even when it takes longer.',
 start='One standard route and one comfort-focused alternative. Show the additional travel time, relevant road conditions and confidence in the available data.',
 later='AR guidance, automotive integrations and broad safety predictions. These add complexity before the basic value of the route comparison is established.',
 tradeoff='A more comfortable route can increase travel time. The interface should make that cost explicit and preserve the original route as a clear choice. Where road data is uncertain, the product should say so rather than imply a guarantee.',
 flow=[('Understand the trip','Capture comfort needs and tolerance for a detour.'),('Compare the options','Explain time, road conditions and confidence.'),('Choose with context','Let the traveller make the final route choice.')],
 measures=[('Primary signal','Can participants understand the trade-off and choose a route that matches their stated preference?'),('Supporting signals','Detour acceptance, perceived usefulness and confidence in the explanation.'),('Guardrails','Confusing alerts, unnecessary diversions and attention demanded during travel.')],
 validation='I would begin with route-comparison prototypes and realistic trip scenarios. Participants would explain their choice and what information they still need. That would test the decision experience before investing in a live routing system.',
 risk='The quality of the recommendation depends on road-data coverage and freshness. Missing or conflicting signals, and the difference between comfort and safety, must be visible in the product logic.',
 learning='The first milestone would be evidence that the comparison improves a real decision. A longer roadmap would depend on that result, rather than on the appeal of adding more navigation features.'),
 dict(slug='alexa-plus', name='Alexa+', category='Consumer AI', color='#e9e8f0', title='From Voice Assistant to Visual AI Companion', short='Exploring when showing can make a voice interaction more useful.', question='Does an avatar help more than a simple visual response?', focus='Interaction design & experiment framing',
 problem='Some learning and storytelling tasks may benefit from showing as well as speaking. The opportunity is to identify those tasks and test which visual format actually helps, rather than assuming animation always improves the experience.',
 hypothesis='A visual response could improve comprehension or completion of a parent-guided learning activity. An animated companion should earn its place by adding value beyond voice alone and simple visual cards.',
 start='One parent-guided learning activity on an existing display. Compare voice-only, simple visual cards and an animated avatar within the same task.',
 later='An avatar marketplace, licensed characters and spatial hardware. These depend on demonstrated value, repeat usefulness and a responsible interaction model.',
 tradeoff='Expressiveness can make an interaction easier to follow, but can also distract or add latency. More time spent is not automatically a better outcome, especially for children. The design should support completion and clear stopping points.',
 flow=[('Set a small task','Choose a bounded, parent-guided activity.'),('Compare formats','Use the same task across three response styles.'),('Evaluate usefulness','Assess understanding and parent satisfaction.')],
 measures=[('Primary signal','Task comprehension or successful completion, compared across response formats.'),('Supporting signals','Parent satisfaction, clarity and willingness to use the activity again.'),('Guardrails','Distraction, inappropriate responses, latency and excessive encouragement to continue.')],
 validation='I would compare the three formats using the same activity and collect both task results and parent feedback. A follow-up session would help distinguish useful repeat use from first-session novelty.',
 risk='The concept must account for children’s privacy, content suitability and emotional dependency. A companion-like appearance should not imply a substitute for human relationships. Those constraints influence the experience, not just the launch checklist.',
 learning='The decision to expand should follow a useful improvement over simpler alternatives. If cards perform just as well as an avatar, the simpler format would be a reasonable product choice.'),
 dict(slug='skyserve', name='SkyServe', category='Service design', color='#e2eaed', title='Your Airport, Brought to You.', short='Making food and essentials easier to reach inside the terminal.', question='Can delivery be dependable within a passenger’s boarding window?', focus='Accessibility & fulfilment design',
 problem='Passengers with limited mobility or little time before boarding may struggle to reach food and essential items across a terminal. Distance, queues and uncertainty can turn a simple purchase into a difficult decision.',
 hypothesis='A limited airport ordering service could improve access if it can reliably fulfil orders within the passenger’s available time, at a cost that works for customers, merchants and the delivery operation.',
 start='One terminal, a limited set of categories, mobile web ordering and pickup or delivery to designated locations. Order acceptance depends on available fulfilment time.',
 later='Broad service categories, duty-free expansion and multi-airport rollout. A dependable pilot should precede wider operational complexity.',
 tradeoff='More coverage increases choice but also delivery distance and variability. The first service should accept fewer orders reliably rather than promise coverage it cannot fulfil. Delivery charges make convenience and accessibility the core value—not an unsupported claim of lower prices.',
 flow=[('Check the window','Confirm location and time available before boarding.'),('Accept a feasible order','Match merchant preparation and delivery capacity.'),('Complete the handoff','Track progress and handle delays clearly.')],
 measures=[('Primary signal','Orders fulfilled within the promised window, with a clear definition of successful handoff.'),('Supporting signals','Passenger satisfaction, cancellations and merchant reliability.'),('Business guardrails','Contribution per order after fulfilment, payment, refund and support costs.')],
 validation='I would start with a service simulation and a limited operational pilot, subject to airport and merchant participation. The pilot would track the complete order journey, especially preparation delays, gate changes and failed handoffs.',
 risk='The hardest dependency is operational coordination: airport access, merchant preparation, delivery capacity and changing passenger locations. Orders that no longer fit the available time need a clear cancellation and refund process.',
 learning='A successful pilot would establish where the service can make a dependable promise. Category and terminal expansion should follow proven fulfilment performance and sustainable economics.'),
 dict(slug='kitchen-genie', name='Kitchen-Genie', category='Everyday decisions', color='#e6ece2', title='Your kitchen, one step ahead.', short='Turning the ingredients you already have into a useful meal decision.', question='Do helpful suggestions outweigh the effort of inventory upkeep?', focus='Habit formation & MVP scope',
 problem='Households can overlook perishable ingredients while deciding what to cook. More recipes do not necessarily resolve that problem; suggestions need to fit the ingredients, time and preferences of the household.',
 hypothesis='A short set of “use this first” suggestions could help people use existing ingredients. The value depends on those suggestions being useful enough to justify keeping the inventory reasonably accurate.',
 start='A small list of perishables and a few relevant meal suggestions. Make it easy to correct quantities and remove ingredients that have already been used.',
 later='Extensive meal planning, connected appliances, grocery integrations and advanced personalization. These should follow evidence that the core inventory-to-meal habit is useful.',
 tradeoff='More detailed inventory could improve recommendations while demanding more user effort. The first version should find the minimum information needed to make a helpful suggestion, rather than requiring a complete digital copy of the kitchen.',
 flow=[('Add a few ingredients','Start with the perishables that need attention.'),('Choose a useful suggestion','Offer a small, relevant set of meal options.'),('Update after cooking','Keep the next suggestion grounded in what remains.')],
 measures=[('Primary signal','Suggested meals actually cooked using ingredients already available.'),('Supporting signals','Time to choose a meal, inventory-update effort and repeat usage.'),('Guardrails','Incorrect inventory, repetitive suggestions and overconfident freshness or dietary advice.')],
 validation='I would test the workflow with a small perishable-food list before expanding the feature set. A short diary study could capture what people cook, what they correct and whether inventory upkeep becomes a reason to stop using it.',
 risk='Inventory can quickly become inaccurate. Photo or receipt input may help, but does not remove the need for correction. Freshness information must allow uncertainty and user judgment rather than promise food safety.',
 learning='The next investment should depend on whether users return to the core workflow. Measured food-waste reduction would require a defined baseline and observation period; it is an intended benefit, not a result claimed here.')
]

def page(title, description, body, color=None):
    accent=f' style="--project-bg:{color}"' if color else ''
    return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{escape(description,quote=True)}"><meta name="theme-color" content="#f7f6f2"><title>{escape(title)} · Labhanshu Vyas</title><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="styles.css"><script src="script.js" defer></script></head>
<body{accent}><a class="skip-link" href="#main">Skip to content</a>{header()}{body}{footer()}</body></html>'''

def header():
    return '''<header class="nav-shell"><div class="container nav-inner"><a class="brand" href="index.html" aria-label="Labhanshu Vyas home"><span class="brand-mark" aria-hidden="true">lv.</span><span>LABHANSHU VYAS</span></a><button class="nav-toggle" aria-expanded="false" aria-controls="navigation" aria-label="Toggle navigation">Menu</button><nav class="nav-links" id="navigation" aria-label="Main navigation"><a href="index.html#work">Work</a><a href="index.html#about">About</a><a href="index.html#experience">Experience</a><a href="index.html#skills">Skills</a><a href="index.html#contact" class="nav-contact">Contact</a></nav></div></header>'''

def contact():
    return f'''<section id="contact" class="contact"><div class="container"><p class="eyebrow">Open to the next problem</p><h2>Let's build something useful.</h2><p>I'm interested in early-career Product and APM opportunities where I can learn quickly, work closely with strong teams and contribute across technology and product.</p><div class="contact-links"><a href="mailto:labhanshuvyas21@gmail.com">Email</a><a href="https://www.linkedin.com/in/labhanshu-vyas/" target="_blank" rel="noopener">LinkedIn</a><a href="{RESUME}" target="_blank" rel="noopener">Résumé</a></div></div></section>'''

def footer():
    return '<footer class="footer">© <span data-year>2026</span> Labhanshu Vyas · Product portfolio</footer>'

def card(p, index):
    return f'''<article class="project-card" style="--project-bg:{p['color']}"><a class="project-art" href="{p['slug']}.html" aria-label="Read {p['name']} case study"><img src="assets/{p['slug']}-report-thumb.webp" width="1484" height="1060" loading="lazy" decoding="async" alt="{p['name']} visual concept report"></a><div class="project-body"><div class="project-meta"><span>{index:02d} / {p['name']}</span><span>Independent concept</span></div><h3><a href="{p['slug']}.html">{p['title']}</a></h3><p>{p['short']}</p><div class="project-question"><span>The product question</span>{p['question']}</div><a class="project-link" href="{p['slug']}.html">Read the case study <span aria-hidden="true">↗</span></a></div></article>'''

def scope_visual():
    return '''<div class="feature-visual" aria-label="Client project contribution summary"><div class="feature-visual-head"><span>CONTRIBUTION MAP</span><span class="mono">01—03</span></div><div class="scope-row"><span class="scope-number">01</span><div><b>Understand the workflow</b><span>Business requirements &amp; user stories</span></div></div><div class="scope-row"><span class="scope-number">02</span><div><b>Build the solution</b><span>Billing &amp; inventory management</span></div></div><div class="scope-row"><span class="scope-number">03</span><div><b>Make the work visible</b><span>SQL &amp; Power BI reporting</span></div></div></div>'''

def home():
    cards=''.join(card(p,i+1) for i,p in enumerate(PROJECTS))
    body=f'''<main id="main"><section class="hero"><div class="container"><div class="hero-grid"><div><p class="eyebrow">Product · Technology · Data</p><h1 class="hero-name">Labhanshu Vyas</h1><p class="hero-tagline">Product thinking. Technical grounding. Practical delivery.</p><p class="hero-copy">I turn business and user problems into clear requirements, focused product decisions and working solutions. My background spans client software, data analysis and independent product concepts.</p><div class="button-row"><a class="button primary" href="#work">Explore the work <span aria-hidden="true">↓</span></a><a class="button" href="{RESUME}" target="_blank" rel="noopener">Résumé <span aria-hidden="true">↗</span></a></div></div><div class="hero-gallery"><div class="gallery-caption"><span>Product ideas, made visible</span><span>01 / 04</span></div><a class="gallery-main" href="google-maps.html" aria-label="Explore the Google Maps concept"><img src="assets/google-maps-report-thumb.webp" width="1484" height="1060" fetchpriority="high" alt="Google Maps safety and comfort navigation concept"></a><div class="gallery-small"><a href="alexa-plus.html" aria-label="Explore the Alexa+ concept"><img src="assets/alexa-plus-report-thumb.webp" width="1484" height="1060" alt="Alexa+ visual companion concept"></a><a href="kitchen-genie.html" aria-label="Explore the Kitchen-Genie concept"><img src="assets/kitchen-genie-report-thumb.webp" width="1484" height="1060" alt="Kitchen-Genie ingredient and meal planning concept"></a></div><div class="gallery-foot"><span>Independent explorations</span><i aria-hidden="true"></i><span>2026</span></div></div></div><div class="discipline-strip"><div><span>Business workflows</span>Client delivery</div><div><span>Everyday decisions</span>Product concepts</div><div><span>Technical foundation</span>Software &amp; data</div></div></div></section>
<section class="section work-section" id="work"><div class="container"><div class="section-heading"><div><p class="eyebrow">Selected work</p><h2>Practical work.<br>Thoughtful possibilities.</h2></div><p>Client experience and independent concepts, with the contribution and scope of each made clear.</p></div><article class="feature-project"><div><p class="eyebrow">Client work / M.S. Corporation</p><h3>Billing and inventory,<br>from requirements<br>to implementation.</h3><p>A business workflow project connecting client needs, software delivery and reporting.</p><p class="role">Freelance Product Owner &amp; Lead Developer</p><a class="button" href="client-work.html">Explore the contribution <span aria-hidden="true">↗</span></a></div>{scope_visual()}</article><div class="exploration-head"><p class="eyebrow">Independent product explorations</p><p>Concepts, hypotheses and proposed validation—not launched products.</p></div><div class="project-grid">{cards}</div></div></section>
<section class="section about-section" id="about"><div class="container about-grid"><div class="about-copy"><p class="eyebrow">A little context</p><h2>Where technology<br>meets people.</h2><p>My background is in Information Technology, with experience in software development, data analysis and client-facing delivery. Working on business workflows drew me toward product management: <strong>understanding what users need, deciding what to prioritize and making those decisions clear enough to build.</strong></p><p>I bring technical fluency, structured problem-solving and experience translating requirements into implementation. I’m particularly interested in everyday decisions and workflows where better product design can reduce effort.</p></div><div><div class="fact-block"><h3>Education</h3><p><strong>B.Tech — Information Technology</strong><br>Chameli Devi Group of Institute · RGPV University<br>2020–2024 · CGPA 8.28/10</p></div><div class="fact-block"><h3>Certificates</h3><ul><li>Google Project Management Professional Certificate</li><li>AWS Academy Cloud Foundation</li><li>NPTEL — Cryptography &amp; Network Security</li></ul></div></div></div></section>
<section class="section" id="experience"><div class="container"><div class="section-heading"><div><p class="eyebrow">Experience &amp; projects</p><h2>The work behind<br>the perspective.</h2></div></div><article class="timeline-item"><div class="timeline-date">Feb. 2025 — Present<span>Freelance</span></div><div class="timeline-content"><h3>M.S. Corporation Pvt. Ltd.</h3><p class="job-role">Product Owner &amp; Lead Developer</p><ul><li>Led delivery of an automated <strong>billing and inventory management product</strong> for a business client.</li><li>Worked with business owners to understand workflows and translate needs into <strong>requirements and user stories</strong>.</li><li>Built SQL and Power BI dashboards to analyse sales, inventory turnover and operational performance.</li></ul><a class="inline-link" href="client-work.html">Read the contribution summary ↗</a></div></article><article class="timeline-item"><div class="timeline-date">Jul. 2024 — Jan. 2025<span>Internship</span></div><div class="timeline-content"><h3>Tech Brothers Pvt. Ltd.</h3><p class="job-role">Software Engineer Intern</p><ul><li>Collaborated with international clients to translate customer requirements into <strong>technical user stories</strong>.</li><li>Contributed to e-commerce features including order tracking and inventory management.</li><li>Automated document-generation and reporting workflows using Python and Microsoft Office tools.</li></ul></div></article><article class="timeline-item"><div class="timeline-date">Jan. 2024 — May 2024<span>University project</span></div><div class="timeline-content"><h3>Unraveling the Twittersphere</h3><p class="job-role">Data &amp; Product Analyst</p><ul><li>Analysed tweet and hashtag data with Python, Pandas and VADER sentiment analysis.</li><li>Built an interactive Power BI dashboard to interpret positive, negative and neutral sentiment by hashtag.</li><li>Worked in a four-person team across data analysis and frontend presentation.</li></ul></div></article><article class="timeline-item"><div class="timeline-date">Nov. 2022 — Jan. 2023<span>University project</span></div><div class="timeline-content"><h3>Virtual Buddy</h3><p class="job-role">Product Lead &amp; Core Developer</p><ul><li>Led a four-person team building a voice-based assistant using Python, NLP and REST APIs.</li><li>Created initial product requirements and development structure, then tested and iterated on the prototype.</li></ul></div></article></div></section>
<section class="section skills-section" id="skills"><div class="container"><div class="section-heading"><div><p class="eyebrow">Toolkit</p><h2>Across product,<br>data and delivery.</h2></div></div><div class="skills-grid"><div><p class="skill-index">01 / PRODUCT</p><h3>Find the right problem.</h3><ul><li>Product discovery</li><li>Problem framing</li><li>User research</li><li>Product strategy</li><li>MVP definition</li><li>Prioritization</li></ul></div><div><p class="skill-index">02 / DATA</p><h3>Make it understandable.</h3><ul><li>Python · SQL</li><li>Pandas</li><li>Power BI</li><li>Data analysis</li><li>Sentiment analysis</li></ul></div><div><p class="skill-index">03 / TECHNOLOGY</p><h3>Connect idea to build.</h3><ul><li>C++ · APIs</li><li>NLP · AI/ML</li><li>Software development</li><li>Cloud foundations</li></ul></div><div><p class="skill-index">04 / EXECUTION</p><h3>Move work forward.</h3><ul><li>Project management</li><li>Team leadership</li><li>Client collaboration</li><li>Requirements gathering</li><li>Communication</li><li>Adaptability</li></ul></div></div></div></section>
<section class="section leadership"><div class="container leadership-grid"><div><p class="eyebrow">Beyond technology</p><blockquote>“When the obvious plan disappears, change the plan — not the goal.”</blockquote></div><div class="leadership-text"><p>As a national-level netball player and school sports captain, I learned that leadership is often less about having the strongest individual player and more about understanding the team you actually have.</p><p>When several stronger players moved into a higher age group, I redistributed responsibilities around the younger players’ strengths and focused on confidence as much as execution.</p><p>That experience shapes how I approach product work: understand the constraints, work with the people available and adapt the plan without losing sight of the goal.</p></div></div></section>{contact()}</main>'''
    (ROOT/'index.html').write_text(page('Product portfolio','Labhanshu Vyas — product thinking, technical grounding and practical delivery. Client work and independent product concepts.',body),encoding='utf-8')

def viewer():
    return '''<dialog class="report-dialog" id="reportViewer" aria-labelledby="viewerTitle"><div class="viewer-toolbar"><span class="viewer-title" id="viewerTitle">Visual product report</span><div class="viewer-controls"><button type="button" data-zoom="out" aria-label="Zoom out">−</button><output aria-label="Zoom level" aria-live="polite">100%</output><button type="button" data-zoom="in" aria-label="Zoom in">+</button><button type="button" data-zoom="fit">Fit</button><button type="button" data-zoom="actual">100%</button><button type="button" data-close-viewer aria-label="Close report">Close ×</button></div></div><p class="viewer-status" role="status">Loading the full-resolution report…</p><div class="viewer-viewport" aria-label="Scrollable report"><div class="viewer-canvas"><img id="viewerImage" alt="Visual product report" hidden></div></div><p class="viewer-help">Use + and − to zoom, then scroll to read. Press Escape to close.</p></dialog>'''

def section(id,title,content,label=None):
    lead=f'<p class="reading-label">{label}</p>' if label else ''
    return f'<section class="case-section" id="{id}">{lead}<h2>{title}</h2>{content}</section>'

def case_page(p,next_p):
    steps=''.join(f'<div class="process-step"><b>0{i+1}</b><h3>{t}</h3><p>{d}</p></div>' for i,(t,d) in enumerate(p['flow']))
    measures=''.join(f'<div><dt>{t}</dt><dd>{d}</dd></div>' for t,d in p['measures'])
    sections=section('problem','Start with the decision.',f'<p>{p["problem"]}</p><div class="case-note"><strong>Working hypothesis</strong><br>{p["hypothesis"]}</div>','01 / PROBLEM & HYPOTHESIS')
    sections+=section('scope','A smaller first version.',f'<div class="decision-grid"><div class="decision-item"><h3>Start here</h3><p>{p["start"]}</p></div><div class="decision-item"><h3>Leave for later</h3><p>{p["later"]}</p></div></div><div class="process" aria-label="Proposed user journey">{steps}</div>','02 / PROPOSED SCOPE')
    sections+=section('tradeoff','Make the trade-off explicit.',f'<p>{p["tradeoff"]}</p>','03 / PRODUCT JUDGMENT')
    sections+=section('validation','Test usefulness before scale.',f'<p>{p["validation"]}</p><dl class="measure-list">{measures}</dl>','04 / PROPOSED VALIDATION')
    sections+=section('unknown','The assumption to challenge.',f'<p>{p["risk"]}</p>','05 / HARDEST UNKNOWN')
    sections+=section('next','What would change the plan?',f'<p>{p["learning"]}</p><p class="case-note">This is an independent product exploration. Interfaces are illustrative, and the tests described here are proposed. The report’s benefits and roadmap are aspirations, not measured outcomes or commitments from the named companies.</p>','06 / NEXT DECISION')
    body=f'''<main id="main"><section class="case-top"><div class="container"><a class="back-link" href="index.html#work">← Back to selected work</a><div class="case-hero"><p class="eyebrow">{p['name']} / Independent product concept</p><h1>{p['title']}</h1><p class="case-lead">{p['short']}</p><div class="case-meta"><div><span>Project type</span>Independent exploration</div><div><span>Focus</span>{p['focus']}</div><div><span>Status</span>Concept · Not launched</div></div></div></div></section><section class="case-visual"><div class="container report-teaser"><img src="assets/{p['slug']}-report-thumb.webp" width="1484" height="1060" alt="{p['name']} visual report overview"><div><p class="eyebrow">The concept at a glance</p><h2>{p['question']}</h2><p>The visual report presents the broader idea. The thinking below narrows it to an initial scope, a trade-off and a proposed test.</p><button class="button primary report-open" type="button" data-report="assets/{p['slug']}-report-full.webp" data-title="{escape(p['name'],quote=True)} visual product report">Open full report <span aria-hidden="true">⤢</span></button><noscript><p><a class="inline-link" href="assets/{p['slug']}-report-full.webp">View the full report image</a></p></noscript></div></div></section><div class="container case-body"><nav class="case-index" aria-label="Case study sections"><p class="eyebrow">Inside the thinking</p><a href="#problem">01 · Problem</a><a href="#scope">02 · First scope</a><a href="#tradeoff">03 · Trade-off</a><a href="#validation">04 · Validation</a><a href="#unknown">05 · Unknown</a><a href="#next">06 · Next decision</a></nav><div>{sections}</div></div><section class="case-next"><div class="container"><div><p class="eyebrow">Next exploration</p><h3>{next_p['name']}</h3></div><a class="button" href="{next_p['slug']}.html">Explore the case study <span aria-hidden="true">↗</span></a></div></section></main>{viewer()}'''
    (ROOT/(p['slug']+'.html')).write_text(page(p['name']+' — '+p['title'],p['short'],body,p['color']),encoding='utf-8')

def client_page():
    content=section('context','A business workflow, end to end.','<p>This freelance project focused on an automated billing and inventory management product for a business client. My role combined understanding business requirements, leading development and making operational information easier to interpret.</p>','01 / CONTEXT')
    content+=section('contribution','My contribution.','<div class="process"><div class="process-step"><b>01</b><h3>Requirements</h3><p>Worked with business owners to understand workflow needs and translate them into requirements and user stories.</p></div><div class="process-step"><b>02</b><h3>Implementation</h3><p>Led delivery of billing and inventory management functionality.</p></div><div class="process-step"><b>03</b><h3>Reporting</h3><p>Built SQL and Power BI dashboards for sales, inventory turnover and operational performance.</p></div></div>','02 / SCOPE OF WORK')
    content+=section('connection','Connecting business and technology.','<p>The work brought together client conversations, structured requirements and implementation. That connection is central to my interest in product roles: understanding a workflow well enough to communicate what needs to be built and why it matters to the people using it.</p>','03 / PRODUCT PERSPECTIVE')
    content+=section('boundaries','What this summary covers.','<p>This page describes my role and the work delivered. It does not claim a measured efficiency improvement: a defined baseline, sample and measurement period are not included here.</p><p>No client records or reconstructed product screenshots are displayed. The contribution map summarizes responsibilities rather than representing a live interface.</p>','04 / SCOPE OF THE CASE STUDY')
    body=f'''<main id="main"><section class="case-top"><div class="container"><a class="back-link" href="index.html#work">← Back to selected work</a><div class="case-hero"><p class="eyebrow">M.S. Corporation / Client work</p><h1>Billing and inventory,<br>from requirements<br>to implementation.</h1><p class="case-lead">A contribution summary spanning client requirements, software delivery and operational reporting.</p><div class="case-meta"><div><span>Role</span>Product Owner &amp; Lead Developer</div><div><span>Engagement</span>Freelance</div><div><span>Tools</span>SQL · Power BI · Software development</div></div></div></div></section><section class="container feature-project"><div><p class="eyebrow">Scope of contribution</p><h3>Understand the business.<br>Make it buildable.</h3><p>Requirements, implementation and reporting connected within one client engagement.</p></div>{scope_visual()}</section><div class="container case-body"><nav class="case-index" aria-label="Case study sections"><p class="eyebrow">Inside the work</p><a href="#context">01 · Context</a><a href="#contribution">02 · Contribution</a><a href="#connection">03 · Perspective</a><a href="#boundaries">04 · Scope</a></nav><div>{content}</div></div><section class="case-next"><div class="container"><div><p class="eyebrow">Independent product exploration</p><h3>Google Maps</h3></div><a class="button" href="google-maps.html">Explore the concept <span aria-hidden="true">↗</span></a></div></section></main>'''
    (ROOT/'client-work.html').write_text(page('Billing & inventory — client contribution','Client requirements, billing and inventory software delivery, and SQL / Power BI reporting.',body),encoding='utf-8')

if __name__=='__main__':
    home()
    client_page()
    for i,p in enumerate(PROJECTS):
        case_page(p,PROJECTS[(i+1)%len(PROJECTS)])
    print('Built homepage and 5 project pages.')
